### ISSUE TITLE
unnecessary code?

### ISSUE THREAD

**Issue by theiliad** [11ty/api-screenshot#1]
I feel like this piece is doing nothing...

https://github.com/11ty/api-screenshot/blob/36407cf678a8c1633b0f816ca59a582bdd78c7b8/functions/screenshot.js#L43-L45

**Comment by zachleat** [comment]
haha yeah. that should be options.quality I think *🦆*

**Comment by theiliad** [comment]
> haha yeah. that should be options.quality I think _🦆_

So right now will the try/catch always run the catch? :D

**Comment by theiliad** [comment]
> So right now will the try/catch always run the catch? :D

Well I guess only at times when the format is jpg

**Comment by zachleat** [comment]
it shouldn’t do anything I don’t think—it’s just a leaky global var that isn’t used

it probably defaults the quality to 100 if it isn’t specified.

**Comment by zachleat** [comment]
Fixed, thanks!
