### ISSUE TITLE
CSS features seem to be unsupported on headless Chromium

### ISSUE THREAD

**Issue by davidsneighbour** [11ty/api-screenshot#12]
I am pretty sure that this is the wrong place to open this issue and not a problem with your scripts, but somehow it might be helpful to see whatever solution this brings for others: I am using a specific CSS3-feature that seems to be broken in the screenshots.

[Screenshot](https://v1.screenshot.11ty.dev/https%3A%2F%2Fkollitsch.de%2Fblog%2F2022%2Fcreating-a-gpg-key-for-github-gitlab-deployment%2F/opengraph/_20210803/):

![_20210803](https://user-images.githubusercontent.com/83281/157259483-5455a840-4ddc-4ecc-b073-23fa2bdfa39f.jpeg)

Original (with Chrome browser loaded):

![Screenshot 2022-03-08 at 21-37-05 Creating a GPG Key for Github Gitlab Deployment - kollitsch de](https://user-images.githubusercontent.com/83281/157259617-a2a0364b-f897-485a-aff8-e549c5f23859.png)

Could you maybe point me in a direction what exactly is the issue here?

Problems:
- dark theme is default, light theme is used (cache? I just changed today to the dark theme as default, but adding random characters to the URL won't load a dark theme screenshot)
- background-clip is not working - [code](https://github.com/davidsneighbour/kollitsch.de/blob/b72dc480a37e91171efe97044871037dde1c2436/assets/scss/_utilities.scss#L25)

Is the headless Chrome somehow in-capacitated in regards to specific features? I thought the used browser in puppeteer is the latest version...

**Comment by zachleat** [comment]
Can you provide the URL of the broken page?

**Comment by zachleat** [comment]
Chromium Version is here: https://github.com/alixaxel/chrome-aws-lambda#versioning

**Comment by davidsneighbour** [comment]
https://v1.screenshot.11ty.dev/https%3A%2F%2Fkollitsch.de%2Fblog%2F2022%2Fcreating-a-gpg-key-for-github-gitlab-deployment%2F/opengraph/_20210803/

The issue comes up too when I run an e2e testing tool over the site (Cypress.io) so my guess currently is, that the browser needs a flag enabled and they disable these styles for speed optimisation.

**Comment by davidsneighbour** [comment]
This was my own fault. I misread the info on caniuse.com as "it's working" when it's actually [only working with `-webkit` prefix](https://caniuse.com/?search=background-clip). I guess selection of the default theme too is based on a feature not enabled in Chrome. Closing this, sorry.

**Comment by zachleat** [comment]
No worries at all! Appreciate you coming back to update!
