### ISSUE TITLE
Error: Invalid `url`: .netlify

### ISSUE THREAD

**Issue by scottwater** [11ty/api-screenshot#3]
Is there something I have to configure in Netlify to have it skip the .netlify/functions/screenshots when making a request for a screenshot?

Calling the function with this in the path results in an error Invalid `url`: .netlify

Thanks.

**Comment by zachleat** [comment]
Note the cleaner redirects in here: https://github.com/11ty/api-screenshot/blob/94d73835d1ce5a2ab08d150aeca52a7e7c2e68be/netlify.toml#L4

Do you have those in place?

**Comment by zachleat** [comment]
The other thing I would make sure is that you’re url encoding the target URL.

JS has a `encodeURI` function by default. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURI

Nunjucks has a `urlencode` filter https://mozilla.github.io/nunjucks/templating.html#urlencode

**Comment by zachleat** [comment]
Otherwise you can DM me the live URL (somehow?) and I can have a closer look

**Comment by scottwater** [comment]
Hi Zach,

Here is are the steps I took:

1. I clicked the 'Deploy to Netlify' here: https://www.zachleat.com/web/screenshots/
2. I downloaded the source from Github and removed the redirects
3. Redeployed the changes (My repo: https://github.com/scottwater/api-screenshot)

Here are a couple of URLs I have tested

- https://cocky-brown-b1def5.netlify.app/https%3A%2F%2Fscottw.com
- https://cocky-brown-b1def5.netlify.app/https%3A%2F%2Fwww.11ty.dev%2Fdocs%2F/small/9:16/larger/

The first should just be my personal site, https://scottw.com and the second I copied from your example.

If I added .netlify/function/screenshot to the URL, it seems to trigger the function, but then fails to grab the correct URL

https://cocky-brown-b1def5.netlify.app/.netlify/functions/screenshot/https%3A%2F%2Fscottw.com 

<img width="1496" alt="Failed Curl Request - Invalid `url`: .netlify" src="https://user-images.githubusercontent.com/188069/128616715-9d3272b4-3b78-4baa-90b0-3d19d5605b49.png">


Thanks,
Scott

**Comment by zachleat** [comment]
The screenshot code assumes the service lives at `/`, so in that way it needs the redirects.

If you want it to live in `/.netlify/functions/screenshot/` you’ll need to change this line https://github.com/11ty/api-screenshot/blob/94d73835d1ce5a2ab08d150aeca52a7e7c2e68be/functions/screenshot.js#L57

**Comment by zachleat** [comment]
That said, you can use a `_redirects` file instead of `netlify.toml` if you want!

**Comment by scottwater** [comment]
Thanks.

I changed the line before split path to this:

```js
  const path = event.path.replace("/.netlify/functions/screenshot", "");
  let pathSplit = path.split("/").filter((entry) => !!entry);
```

So now it should work regardless of the standard Netlify location or not. 

I was assuming clicking the netlify deploy button would just work. Sorry for the confusion. 

For anyone else who bumps into this, I added this to my .toml and it makes it possible to remove the .netlify from the URL.

```toml
[[redirects]]
from =  "/*"
to = "/.netlify/functions/screenshot/:splat"
status = 200
```

Thanks for sharing the code!

**Comment by zachleat** [comment]
OH, I finally understand. The Deploy to Netlify button _should_ work without extra work so this is definitely a bug (reopening).

The awkwardness here is between the `v1` branch and the `main` branch. `v1` has the exact code you mentioned.

https://github.com/11ty/api-screenshot/blob/v1/netlify.toml

**Comment by zachleat** [comment]
Alright, I changed `main` to be the primary branch on GitHub (used in the Deploy to Netlify button) which now has the right redirects in netlify.toml.

The `no-version` branch is now the production branch on `screenshot.11ty.dev` (has the custom redirects to `v1.screenshot.11ty.dev`).

This should fix the button—thanks for walking through it!
